// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Sem fallback pra DEST_SUPABASE_*/STATIC_SUPABASE_*: esta é a conexão
// privilegiada (service role). Prefira falhar alto a resolver silenciosamente
// para um projeto de staging/destino esquecido no ambiente.
function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.error(`[Supabase] Administrative runtime configuration unavailable (${missing.length} item(s)).`);
    // Mensagem amigável: nunca vazar nome de variável de ambiente para a UI.
    const error = new Error(
      'Esta ação administrativa está temporariamente indisponível porque a chave de serviço do Supabase não está configurada neste ambiente. Os demais recursos continuam funcionando normalmente.',
    );
    error.name = 'ServiceRoleUnavailableError';
    throw error;
  }

  const serviceKey = SUPABASE_SERVICE_ROLE_KEY;
  return createClient<Database>(SUPABASE_URL, serviceKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      fetch: (input, init) => {
        const headers = new Headers(init?.headers);
        if (
          serviceKey.startsWith('sb_') &&
          headers.get('Authorization') === `Bearer ${serviceKey}`
        ) {
          headers.delete('Authorization');
        }
        headers.set('apikey', serviceKey);
        return fetch(input, { ...init, headers });
      },
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
